name: Notification Service CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

permissions:
  contents: read
  packages: write

env:
  DOTNET_VERSION: "8.0.x"
  SOLUTION_PATH: "./NotificationService/NotificationService.sln"
  IMAGE_NAME: "notification-service"

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release

      - name: Test
        run: dotnet test ${{ env.SOLUTION_PATH }} --configuration Release --no-restore --no-build --verbosity normal

  containerize_kaniko:
    needs: build_test
    runs-on: ubuntu-latest

    container:
      image: gcr.io/kaniko-project/executor:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare auth for GHCR
        shell: bash
        run: |
          mkdir -p /kaniko/.docker
          cat > /kaniko/.docker/config.json <<'EOF'
          {
            "auths": {
              "ghcr.io": {
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              }
            }
          }
          EOF

      - name: Build & Push image with Kaniko
        shell: bash
        run: |
          OWNER_LC="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          REPO_LC="$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')"

          IMAGE="ghcr.io/${OWNER_LC}/${REPO_LC}"

          CONTEXT="."
          DOCKERFILE="./NotificationService/NotificationService/Dockerfile"

          # Tagovi: commit SHA + grana (develop/main)
          TAG_SHA="${{ github.sha }}"
          TAG_BRANCH="${{ github.ref_name }}"

          /kaniko/executor \
            --context "${CONTEXT}" \
            --dockerfile "${DOCKERFILE}" \
            --destination "${IMAGE}:${TAG_SHA}" \
            --destination "${IMAGE}:${TAG_BRANCH}" \
            --cache=true
